const seedProducts = [
	{
		title: 'Paper Menus',
		handle: 'paper-menus',
		slug: 'paper-menus',
		description: 'Paper Menus — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001898131/NPIB-42985-Stills-PonPoke-Menu-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'PAPER-MENUS-DEFAULT',
				price: 9023.75,
				compareAtPrice: 12000.0,
				inventory: 28,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Next Day Flyers',
		handle: 'next-day-flyers',
		slug: 'next-day-flyers',
		description: 'Next Day Flyers — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001790909/MXP-30649-Tile-Flyer-Donuts-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'NEXT-DAY-FLYERS-DEFAULT',
				price: 7150.5,
				compareAtPrice: null,
				inventory: 31,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Business Sample Kit',
		handle: 'business-sample-kit',
		slug: 'business-sample-kit',
		description: 'Business Sample Kit — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001800388/NPIB-32217-SmaplekitRevamp-AllProducts-Grid-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'BUSINESS-SAMPLE-KIT-DEFAULT',
				price: 8900.0,
				compareAtPrice: null,
				inventory: 22,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Table Signs',
		handle: 'table-signs',
		slug: 'table-signs',
		description: 'Table Signs — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001893921/MXP-36343-Tabletop-square-Aluminum-tile-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'TABLE-SIGNS-DEFAULT',
				price: 5600.9,
				compareAtPrice: 6500.0,
				inventory: 44,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Bulk Posters',
		handle: 'bulk-posters',
		slug: 'bulk-posters',
		description: 'Bulk Posters — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/image/upload/c_scale,dpr_auto,f_auto,q_60,w_500/180723_Bulk_Posters_EU_',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'BULK-POSTERS-DEFAULT',
				price: 4700.0,
				compareAtPrice: 6000.0,
				inventory: 25,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Pet Cutouts',
		handle: 'pet-cutouts',
		slug: 'pet-cutouts',
		description: 'Pet Cutouts — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001902557/NPIB-50365-Pet-Cut-outs-Tier4-lifestyle-EUSF-Pet-Overview-004',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'PET-CUTOUTS-DEFAULT',
				price: 7200.0,
				compareAtPrice: null,
				inventory: 18,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Waterproof Stickers',
		handle: 'waterproof-stickers',
		slug: 'waterproof-stickers',
		description: 'Waterproof Stickers — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001919209/NPIB-49508-WaterProof-Stickers-Signs-Rectangle-EU-Cat-Search-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'WATERPROOF-STICKERS-DEFAULT',
				price: 3050.0,
				compareAtPrice: null,
				inventory: 33,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Paper Bags With Single Colour Print',
		handle: 'paper-bags-with-single-colour-print',
		slug: 'paper-bags-with-single-colour-print',
		description: 'Paper Bags With Single Colour Print — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001944423/NPIB-51477-Single-Color-Bag-Tile-Overview',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'PAPER-BAGS-WITH-SINGLE-COLOUR-PRINT-DEFAULT',
				price: 5300.0,
				compareAtPrice: 6100.0,
				inventory: 30,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Tabletop Prints',
		handle: 'tabletop-prints',
		slug: 'tabletop-prints',
		description: 'Tabletop Prints — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001872136/NPIB-5450-EU-Tabletop-Prints-Overview-Tile-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'TABLETOP-PRINTS-DEFAULT',
				price: 4100.0,
				compareAtPrice: null,
				inventory: 12,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Paper Sticker Sheets',
		handle: 'paper-sticker-sheets',
		slug: 'paper-sticker-sheets',
		description: 'Paper Sticker Sheets — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001895039/NPIB49084-Transparent-Plastic-SheetStickers-Overview-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'PAPER-STICKER-SHEETS-DEFAULT',
				price: 4350.75,
				compareAtPrice: 5000.0,
				inventory: 37,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Full-Print Paper Bags',
		handle: 'full-print-paper-bags',
		slug: 'full-print-paper-bags',
		description: 'Full-Print Paper Bags — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001946901/NPIB-51477-L2-Full-Print-PaperBags-Tile',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'FULL-PRINT-PAPER-BAGS-DEFAULT',
				price: 6280.0,
				compareAtPrice: 7900.0,
				inventory: 40,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Birthday Banners',
		handle: 'birthday-banners',
		slug: 'birthday-banners',
		description: 'Birthday Banners — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001880116/NPIB-45175-Cons-Feb-Adult-B-day-party-Banner-Tile-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'BIRTHDAY-BANNERS-DEFAULT',
				price: 4500.0,
				compareAtPrice: 5600.0,
				inventory: 21,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Party Bags',
		handle: 'party-bags',
		slug: 'party-bags',
		description: 'Party Bags — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001898113/NPIB-50338-Paper-Bags-Tile-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'PARTY-BAGS-DEFAULT',
				price: 3900.0,
				compareAtPrice: null,
				inventory: 34,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Recycled Paper Labels',
		handle: 'recycled-paper-labels',
		slug: 'recycled-paper-labels',
		description: 'Recycled Paper Labels — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001887657/NPIB45074-Recycled-Labels-Tile-Overview-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'RECYCLED-PAPER-LABELS-DEFAULT',
				price: 3800.0,
				compareAtPrice: null,
				inventory: 29,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Face Cutouts',
		handle: 'face-cutouts',
		slug: 'face-cutouts',
		description: 'Face Cutouts — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001902540/NPIB-50365-Face-Cut-outs-Tier4-lifestyle-EUSF-face-Shape-Overview-005',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'FACE-CUTOUTS-DEFAULT',
				price: 8120.0,
				compareAtPrice: null,
				inventory: 19,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Foamex Menu Cards',
		handle: 'foamex-menu-cards',
		slug: 'foamex-menu-cards',
		description: 'Foamex Menu Cards — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001903011/NPIB-18113-category-tile-rigid-menu-004',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'FOAMEX-MENU-CARDS-DEFAULT',
				price: 6890.0,
				compareAtPrice: 7200.0,
				inventory: 42,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Advertising Flags',
		handle: 'advertising-flags',
		slug: 'advertising-flags',
		description: 'Advertising Flags — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001943513/NPIB-56820-Feather-Sail-Teardrop-flags-T3-EU-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'ADVERTISING-FLAGS-DEFAULT',
				price: 7200.0,
				compareAtPrice: 9500.0,
				inventory: 26,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Personalised Heart Stickers',
		handle: 'personalised-heart-stickers',
		slug: 'personalised-heart-stickers',
		description: 'Personalised Heart Stickers — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001873096/NPIB-41371-Heart-stickers-EU-10x10-Tile-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'PERSONALISED-HEART-STICKERS-DEFAULT',
				price: 3300.0,
				compareAtPrice: null,
				inventory: 20,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Transparent Sticker Sheets',
		handle: 'transparent-sticker-sheets',
		slug: 'transparent-sticker-sheets',
		description: 'Transparent Sticker Sheets — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001940213/NPIB-49084-Sheet-Stickers-Circle-Transparent-3x3-Overview-EU-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'TRANSPARENT-STICKER-SHEETS-DEFAULT',
				price: 4125.5,
				compareAtPrice: null,
				inventory: 33,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Next-Day Posters',
		handle: 'next-day-posters',
		slug: 'next-day-posters',
		description: 'Next-Day Posters — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001734093/MXP-27115-Poster-Tile-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'NEXT-DAY-POSTERS-DEFAULT',
				price: 5500.0,
				compareAtPrice: 6500.0,
				inventory: 28,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Curved Professional Counters',
		handle: 'curved-professional-counters',
		slug: 'curved-professional-counters',
		description: 'Curved Professional Counters — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001898690/NPIB-39197-Curved-professional-counter-EU-small-bothsizes-print-T3-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'CURVED-PROFESSIONAL-COUNTERS-DEFAULT',
				price: 4600.0,
				compareAtPrice: 5000.0,
				inventory: 15,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Paper Stickers',
		handle: 'paper-stickers',
		slug: 'paper-stickers',
		description: 'Paper Stickers — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001894266/NPIB-49346-White-Paper-Stock-Roll-Labels-3x2-Oval-V2-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'PAPER-STICKERS-DEFAULT',
				price: 2950.0,
				compareAtPrice: null,
				inventory: 38,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Front Adhesive Stickers',
		handle: 'front-adhesive-stickers',
		slug: 'front-adhesive-stickers',
		description: 'Front Adhesive Stickers — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001920079/NPIB-48661-Front-Adhesive-Stickers-EU-Tier4-Overview-002',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'FRONT-ADHESIVE-STICKERS-DEFAULT',
				price: 3100.0,
				compareAtPrice: null,
				inventory: 27,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Soap Boxes',
		handle: 'soap-boxes',
		slug: 'soap-boxes',
		description: 'Soap Boxes — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/es-us/S001869976/NPIB-35044-Soap-Box-NA-T4-001?cb=830fc77ee95afc688f5e12a4ba7d314781d4de46',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'SOAP-BOXES-DEFAULT',
				price: 4450.0,
				compareAtPrice: 5800.0,
				inventory: 36,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Bottle Neck Tags',
		handle: 'bottle-neck-tags',
		slug: 'bottle-neck-tags',
		description: 'Bottle Neck Tags — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001901584/NPIB-43973-Bottle-Tags-EU-T3-Tile-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'BOTTLE-NECK-TAGS-DEFAULT',
				price: 3500.0,
				compareAtPrice: null,
				inventory: 30,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Full Custom Performance Tank Top',
		handle: 'full-custom-performance-tank-top',
		slug: 'full-custom-performance-tank-top',
		description: 'Full Custom Performance Tank Top — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001625820/MXP21875-Full-Custom-Tank-Top-DP-Tile-001?cb=f5083f18ea1b5b67cceb3ddf0a2dfa4d1337ad07',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [
			{ name: 'Color', position: 1, values: ['Black', 'White'] },
			{ name: 'Size', position: 2, values: ['S', 'M', 'L'] },
		],
		variants: [
			{
				title: 'Black / S',
				sku: 'FULL-CUSTOM-PERFORMANCE-TANK-TOP-BLACK-S',
				option1: 'Black',
				option2: 'S',
				price: 15500.0,
				compareAtPrice: 18000.0,
				inventory: 12,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
			{
				title: 'White / M',
				sku: 'FULL-CUSTOM-PERFORMANCE-TANK-TOP-WHITE-M',
				option1: 'White',
				option2: 'M',
				price: 16000.0,
				compareAtPrice: null,
				inventory: 17,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 2,
			},
		],
	},
	{
		title: 'Advertising Banners',
		handle: 'advertising-banners',
		slug: 'advertising-banners',
		description: 'Advertising Banners — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001708043/MXP-26838-tile-vinyl-banner2-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'ADVERTISING-BANNERS-DEFAULT',
				price: 8700.0,
				compareAtPrice: 9500.0,
				inventory: 24,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Custom Size Cards',
		handle: 'custom-size-cards',
		slug: 'custom-size-cards',
		description: 'Custom Size Cards — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001926478/NPIB-29051-overview-tile-custom-card-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'CUSTOM-SIZE-CARDS-DEFAULT',
				price: 5200.0,
				compareAtPrice: 6000.0,
				inventory: 19,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Spot UV Swing Tags',
		handle: 'spot-uv-swing-tags',
		slug: 'spot-uv-swing-tags',
		description: 'Spot UV Swing Tags — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001888199/NPIB-43697-Spot-U-Hang-Tags-Circle-Overview-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'SPOT-UV-SWING-TAGS-DEFAULT',
				price: 4700.0,
				compareAtPrice: 5200.0,
				inventory: 35,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Soft Touch Stickers',
		handle: 'soft-touch-stickers',
		slug: 'soft-touch-stickers',
		description: 'Soft Touch Stickers — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001898426/NPIB-48668-Overview-Soft-Touch-NA-T3-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'SOFT-TOUCH-STICKERS-DEFAULT',
				price: 3200.0,
				compareAtPrice: null,
				inventory: 40,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Bodhi Water Bottle – 500 ml',
		handle: 'bodhi-water-bottle-500-ml',
		slug: 'bodhi-water-bottle-500-ml',
		description: 'Bodhi Water Bottle – 500 ml — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://logo-rendering.large-assortment.vpsvc.com/api/v2/platform-products/vistaprint/en-gb/PRD-9EJLGAZGV/sample-image?productVersion=9&selectedOptions%5BSubstrate%20Color%5D=%23000000&size=500&requestor=product-discovery-page',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'BODHI-WATER-BOTTLE-500-ML-DEFAULT',
				price: 7500.0,
				compareAtPrice: 8900.0,
				inventory: 22,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Perfect-Bound Booklets',
		handle: 'perfect-bound-booklets',
		slug: 'perfect-bound-booklets',
		description: 'Perfect-Bound Booklets — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001885985/NPIB-39462-product-tile-perfect-bound-booklets-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'PERFECT-BOUND-BOOKLETS-DEFAULT',
				price: 9800.0,
				compareAtPrice: null,
				inventory: 18,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Sun Ray Sunglasses',
		handle: 'sun-ray-sunglasses',
		slug: 'sun-ray-sunglasses',
		description: 'Sun Ray Sunglasses — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://logo-rendering.large-assortment.vpsvc.com/api/v2/platform-products/vistaprint/en-gb/PRD-ZCXO9RFCZ/sample-image?productVersion=4&selectedOptions%5BSubstrate%20Color%5D=%235588D4&size=500&requestor=product-discovery-page',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'SUN-RAY-SUNGLASSES-DEFAULT',
				price: 8700.0,
				compareAtPrice: 10500.0,
				inventory: 23,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Pheebs Apron',
		handle: 'pheebs-apron',
		slug: 'pheebs-apron',
		description: 'Pheebs Apron — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://logo-rendering.large-assortment.vpsvc.com/api/v2/platform-products/vistaprint/en-gb/PRD-DZQWCLIYY/sample-image?productVersion=12&selectedOptions%5BSubstrate%20Color%5D=%234d4d4d&size=500&requestor=product-discovery-page',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [
			{ name: 'Color', position: 1, values: ['Black', 'White'] },
			{ name: 'Size', position: 2, values: ['S', 'M', 'L'] },
		],
		variants: [
			{
				title: 'Black / S',
				sku: 'PHEEBS-APRON-BLACK-S',
				option1: 'Black',
				option2: 'S',
				price: 11500.0,
				compareAtPrice: null,
				inventory: 20,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
			{
				title: 'White / M',
				sku: 'PHEEBS-APRON-WHITE-M',
				option1: 'White',
				option2: 'M',
				price: 12000.0,
				compareAtPrice: 14500.0,
				inventory: 18,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 2,
			},
		],
	},
	{
		title: 'Elevate Morgan Duotone Polo Shirt',
		handle: 'elevate-morgan-duotone-polo-shirt',
		slug: 'elevate-morgan-duotone-polo-shirt',
		description: 'Elevate Morgan Duotone Polo Shirt — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://logo-rendering.large-assortment.vpsvc.com/api/v2/platform-products/vistaprint/en-gb/PRD-YAVSYE5EZ/sample-image?productVersion=4&selectedOptions%5BSubstrate%20Color%5D=%23000000&size=500&requestor=product-discovery-page',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [
			{ name: 'Color', position: 1, values: ['Black', 'White'] },
			{ name: 'Size', position: 2, values: ['S', 'M', 'L'] },
		],
		variants: [
			{
				title: 'Black / S',
				sku: 'ELEVATE-MORGAN-DUOTONE-POLO-SHIRT-BLACK-S',
				option1: 'Black',
				option2: 'S',
				price: 16500.0,
				compareAtPrice: 19000.0,
				inventory: 10,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
			{
				title: 'White / M',
				sku: 'ELEVATE-MORGAN-DUOTONE-POLO-SHIRT-WHITE-M',
				option1: 'White',
				option2: 'M',
				price: 16000.0,
				compareAtPrice: null,
				inventory: 12,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 2,
			},
		],
	},
	{
		title: 'Full-Custom Tote Bags',
		handle: 'full-custom-tote-bags',
		slug: 'full-custom-tote-bags',
		description: 'Full-Custom Tote Bags — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001599047/MXP-19593-Full-Custom-Tote-Bag-DP-Tile-001?cb=89ab945ba1df4a4e1a1d62c5727f0a8dea239b1c',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [{ name: 'Color', position: 1, values: ['Black', 'White'] }],
		variants: [
			{
				title: 'Black',
				sku: 'FULL-CUSTOM-TOTE-BAGS-BLACK',
				option1: 'Black',
				price: 8500.0,
				compareAtPrice: 9900.0,
				inventory: 25,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
			{
				title: 'White',
				sku: 'FULL-CUSTOM-TOTE-BAGS-WHITE',
				option1: 'White',
				price: 8300.0,
				compareAtPrice: null,
				inventory: 30,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 2,
			},
		],
	},
	{
		title: 'Custom Gift Boxes',
		handle: 'custom-gift-boxes',
		slug: 'custom-gift-boxes',
		description: 'Custom Gift Boxes — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-ca/S001833601/NPIB-40269-MailingBox-001?cb=47ed88e73fb747fb315794009499c652e3836acd',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'CUSTOM-GIFT-BOXES-DEFAULT',
				price: 9600.0,
				compareAtPrice: 12000.0,
				inventory: 16,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Arch Flags',
		handle: 'arch-flags',
		slug: 'arch-flags',
		description: 'Arch Flags — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001867998/NPIB-40100-Event-Arch-EU-Full-Arch-T4-Tile-002',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'ARCH-FLAGS-DEFAULT',
				price: 8800.0,
				compareAtPrice: 10200.0,
				inventory: 29,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Gift Labels',
		handle: 'gift-labels',
		slug: 'gift-labels',
		description: 'Gift Labels — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001935355/NPIB-47710-Name-Tags-T6-Sheet-EU-004',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'GIFT-LABELS-DEFAULT',
				price: 4100.0,
				compareAtPrice: null,
				inventory: 36,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Personalised Tumblers',
		handle: 'personalised-tumblers',
		slug: 'personalised-tumblers',
		description: 'Personalised Tumblers — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001940816/NPIB-35303-coffee-tumbler-product-tile-001',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [],
		variants: [
			{
				title: 'Default',
				sku: 'PERSONALISED-TUMBLERS-DEFAULT',
				price: 9300.0,
				compareAtPrice: 11000.0,
				inventory: 24,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
		],
	},
	{
		title: 'Women’s V-Neck Basketball Jersey',
		handle: 'womens-v-neck-basketball-jersey',
		slug: 'womens-v-neck-basketball-jersey',
		description: 'Women’s V-Neck Basketball Jersey — quality print product available in Nigeria.',
		status: 'PUBLISHED',
		productType: 'Custom',
		vendor: 'Demo Vendor',
		images: [
			{
				src: 'https://cms.cloudinary.vpsvc.com/images/c_scale,dpr_auto,f_auto,q_60,w_500/legacy_dam/en-gb/S001630354/MXP22756-Women-VNeck-Basketball-Jersey-NA-DP-Tile-001?cb=4f474091a90e2ebbd781be8d8895f30bb02a4e6b',
				width: 500,
				height: 500,
				position: 1,
			},
		],
		options: [{ name: 'Size', position: 1, values: ['S', 'M', 'L'] }],
		variants: [
			{
				title: 'S',
				sku: 'WOMENS-V-NECK-BASKETBALL-JERSEY-S',
				option1: 'S',
				price: 14000.0,
				compareAtPrice: 16000.0,
				inventory: 14,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 1,
			},
			{
				title: 'M',
				sku: 'WOMENS-V-NECK-BASKETBALL-JERSEY-M',
				option1: 'M',
				price: 14250.0,
				compareAtPrice: null,
				inventory: 18,
				requiresShipping: true,
				taxable: false,
				available: true,
				position: 2,
			},
		],
	},
];

export default seedProducts;
